packages:
  - apps/*
  - packages/*

peerDependencyRules:
  ignoreMissing:
    - "@expo/dom-webview"
  allowedVersions:
    # expo-share-intent@6.1.1 hasn't updated peerDeps to include ^56 yet but works fine
    expo-share-intent>expo: "56"

onlyBuiltDependencies:
  - '@firebase/util'
  - '@vercel/speed-insights'
  - electron
  - electron-winstaller
  - esbuild
  - msgpackr-extract
  - protobufjs
  - sharp
