packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@firebase/util'
  - '@sentry/cli'
  - '@vercel/speed-insights'
  - electron
  - electron-winstaller
  - esbuild
  - protobufjs
  - sharp
