packages:
  - apps/*
  - packages/*
  - functions

onlyBuiltDependencies:
  - '@firebase/util'
  - '@vercel/speed-insights'
  - electron
  - electron-winstaller
  - esbuild
  - msgpackr-extract
  - protobufjs
  - sharp
peerDependencyRules:
  ignoreMissing:
    - "@expo/dom-webview"
